spring:
  redis:
    host: 192.168.43.141
    port: 6379
  rabbitmq:
    host: 192.168.43.141
    port: 5672
    username: guest
    password: guest
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.43.141:3306/springCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.112:8761/eureka/
  instance:
    prefer-ip-address: true
  instance:
    prefer-ip-address: true
env:
  dev
girl:
  name: 刘容
  age: 23
